---
apiVersion: v1
kind: Service
metadata:
  name: stocks-service
spec:
  type: NodePort
  selector:
    app: stocks-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-service
  labels:
    app: stocks-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocks-service
  template:
    metadata:
      labels:
        app: stocks-service
    spec:
      containers:
      - name: stocks-service
        image: stocks-service-img:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000